### ISSUE TITLE
Modify Street Line Types

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-citymap#166]

**Comment by chriswhong** [comment]
Technically, "unmapped street" includes "record streets".

**Comment by andycochran** [comment]
This is still confusing, as we're using both "mapped" and "on City Map" to describe streets that are documented in the City Map, and "unmapped" to describe streets not documented in the City Map. 

Maybe instead of one "Street Map Layers" layer group we could have a "City Map Layers" (Mapped Streets, Record Streets, Alterations, etc) and "Other Street Layers" (Unmapped Streets, Arterials, Pending Alterations, etc) to differentiate which layers are officially mapped.

**Comment by aenglis** [comment]
We decided to make thing more easier by just including mapped streets and unmapped streets. This will mean removing record streets from map key and symbolizing record streets and unmapped streets in the same manner so that on the map they look indistinguishable. The symbology for both should be the current unmapped street linetype.
