### ISSUE TITLE
Use Glove for mousemove, pointer for mouse end

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-citymap#167]
All map is clickable, should use pointing hand, but could use open hand when moving mouse. @andycochran any other ideas?

**Comment by andycochran** [comment]
It may be enough to simply always have `cursor:pointer` on the map. The map _is_ clickable everywhere. Keeping the pointer while moving the cursor does not imply that the map cannot be dragged. The cursor is always a pointer in ZoLa when all the Zoning Districts are on, unless you hover the water. It'd be nice if we could only have the pointer when hovering NYC, but I'd prefer it always be `pointer` rather than switching to `grab` on mouse move.
